### ISSUE TITLE
Java?

### ISSUE THREAD

**Issue by fdncred** [kaby76/Piggy#5]
Is Java really required? I'm getting this error with PiggyRuntime/PiggyGenerator.
```
1>C:\Users\username\.nuget\packages\antlr4buildtasks\1.0.4\build\Antlr4BuildTasks.targets(131,5): error AC1000: Unknown build error: Cannot find Java home, currently set to 'NOT_SET_IN_ENV' Please set either the JAVA_HOME environment variable, or set a property for JavaHome in your CSPROJ file.
```

**Comment by fdncred** [comment]
For those that don't use java you can do this.

1. Download the Java JDK and install it.
2. Download antlr-4.7.2-complete.jar from [antlr.org](https://www.antlr.org/download.html) and put it in a folder.
3. Edit your csproj files with these entires.
```
    <PropertyGroup>
        <JAVA_HOME>C:\Program Files\Java\jdk-11.0.1</JAVA_HOME>
    </PropertyGroup>

    <PropertyGroup>
        <Antlr4ToolPath>C:\Program Files\Java\javalib\antlr-4.7.2-complete.jar</Antlr4ToolPath>
    </PropertyGroup>
```
I was able to compile PiggyGenerator and PiggyRuntime after these steps.

**Comment by kaby76** [comment]
Well, yes, it's required to build the generator. It is a trade-off. Thanks for the note; I'll update the readme. The reason is that the generator has Antlr grammars. Originally, I was checking in the generated parsers and lexers in source control, but I was reworking on the grammar a lot and wanted it to be more seamless in the build. Antlr4cs is the alternative, as it includes a C# version of the Antlr tool, but I think I mention in the Antlr4BuildTasks project that it is at least one or two years behind the current version of the Java-based Antlr tool.

**Comment by fdncred** [comment]
Bump.  These property groups aren't in your code base.

**Comment by kaby76** [comment]
Thanks, I just added the groups to the PiggyGenerator.csproj, and PiggyRuntime.csproj (all that use Antlr) with conditional guards. I have them set differently for my machine as to not override if already set.
